# Generated by Django 3.0.3 on 2020-06-11 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postedDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
